[package]
name = "kontrolluppgift"
version = "0.1.0"
edition = "2021"
description = "A library for dealing with Skatteverkets data format for Kontrolluppgift"
license= "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.152", features = ["derive"]}

[dev-dependencies]
serde-xml-rs = "0.6.0"
